export const campusMeta = {
    university: {
        name: 'Assam down town University',
        campusName: 'Panikhaiti Campus',
    },
    blocks: [
        { code: 'A', name: 'Kaziranga' },
        { code: 'B', name: 'Manas' },
        { code: 'C', name: 'Pobitora' },
        { code: 'D', name: 'Panidehing' },
        { code: 'E', name: 'Raimona' },
        { code: 'F', name: 'Chakrasila' },
        { code: 'G', name: 'Burachapori' },
        { code: 'H', name: 'Dehing Patkai' },
        { code: 'HE', name: 'Mouling' },
        { code: 'I', name: 'Dibru Saikhowa' },
        { code: 'J', name: 'Nameri' },
        { code: 'K', name: 'Bornadi' },
        { code: 'L', name: 'Orang' },
        { code: 'M', name: 'Amchang' },
        { code: 'SPORTS', name: 'Sports Arena' },
        { code: 'AMP', name: 'Amphitheatre' },
        { code: 'AGRI', name: 'Agri Instruction Cum Research Field' },
    ],
    blockBFacilities: [
        {
            floor: 'Floor 2',
            facilities: [
                'Dean Office, Faculty of Commerce & Management',
                'Commerce & Management Classrooms',
                'Cafeteria',
            ],
        },
        {
            floor: 'Floor 1',
            facilities: [
                'Dean Office, Faculty of Engineering',
                'Engineering Classrooms & Laboratories',
                'Paramedical Classrooms',
            ],
        },
        {
            floor: 'Ground Floor',
            facilities: [
                'IT Cell',
                'Student Help Desk',
                'Discipline of Hospitality & Tourism Management',
                'Directorate of Research',
                'Computer Laboratories',
                'Divyangjan Toilet',
            ],
        },
        {
            floor: 'Floor B1',
            facilities: [
                'Dean Office, Faculty of Computer Technology',
                'Computer Technology Classrooms & Laboratories',
                'Pharmaceutical Science Classrooms',
            ],
        },
        {
            floor: 'Floor B2',
            facilities: [
                'Dean Office, Faculty of Pharmaceutical Science',
                'Pharmaceutical Science Classrooms & Laboratories',
                'Central Instrumentation Facility',
            ],
        },
        {
            floor: 'Floor B3',
            facilities: [
                'Seminar Halls & Laboratories',
                'Paramedical Classrooms',
                'Dream Cafe',
            ],
        },
        {
            floor: 'Floor B4',
            facilities: ['Engineering Laboratories'],
        },
    ],
    labCategories: [
        'Civil Engineering Lab',
        'Chemistry Lab',
        'Computer Lab',
        'Electrical Lab',
        'Electronics Lab',
        'Mechanical Lab',
        'Medical Lab',
        'Physics Lab',
        'Physiotherapy Lab',
        'Biotechnology Lab',
        'Microbiology Lab',
        'Biochemistry Lab',
    ],
    civilLabs: [
        { name: 'Survey Lab', roomNo: 'B005', areaSqm: 66.89 },
        { name: 'Environmental Engineering Lab', roomNo: 'B008', areaSqm: 66 },
        { name: 'Hydraulics Lab', roomNo: 'B004', areaSqm: 66 },
        { name: 'Fluid Mechanics Lab', roomNo: 'B003', areaSqm: 66 },
        { name: 'Solid Mechanics Lab', roomNo: 'B103', areaSqm: 66 },
        { name: 'Material Testing & Evaluation Lab', roomNo: 'B104', areaSqm: 66 },
        { name: 'Geotechnical Engineering Lab', roomNo: 'B102', areaSqm: 74 },
        { name: 'Transportation Engineering Lab', roomNo: 'B101', areaSqm: 74 },
        { name: 'Engineering Geology Lab', roomNo: 'B006', areaSqm: 66.89 },
        { name: 'Drawing Hall / Design Lab', roomNo: 'B224/B002', areaSqm: 147 },
        { name: 'Heat Transfer Lab', roomNo: 'B428', areaSqm: 66 },
        { name: 'Thermal Lab', roomNo: 'B001', areaSqm: 66 },
    ],
    sportsAndGroundVenues: [
        {
            blockCode: 'K',
            zone: 'K Block Activity Zone',
            venueName: 'Snooker Lounge',
            peopleCount: 14,
            capacity: 28,
            crowdLevel: 'MEDIUM',
        },
        {
            blockCode: 'K',
            zone: 'K Block Activity Zone',
            venueName: 'Jironee Brahmaputra Riverview',
            peopleCount: 22,
            capacity: 40,
            crowdLevel: 'MEDIUM',
        },
        {
            blockCode: 'K',
            zone: 'K Block Wellness Zone',
            venueName: 'Library',
            peopleCount: 31,
            capacity: 80,
            crowdLevel: 'LOW',
        },
        {
            blockCode: 'K',
            zone: 'K Block Wellness Zone',
            venueName: 'Gym',
            peopleCount: 26,
            capacity: 35,
            crowdLevel: 'HIGH',
        },
        {
            blockCode: 'K',
            zone: 'K Block Sports Zone',
            venueName: 'Badminton Court',
            peopleCount: 18,
            capacity: 28,
            crowdLevel: 'MEDIUM',
        },
        {
            blockCode: 'K',
            zone: 'K Block Sports Zone',
            venueName: 'Swimming Pool',
            peopleCount: 20,
            capacity: 45,
            crowdLevel: 'LOW',
        },
        {
            blockCode: 'K',
            zone: 'K Block Wellness Zone',
            venueName: 'Yoga Room',
            peopleCount: 16,
            capacity: 30,
            crowdLevel: 'LOW',
        },
        {
            blockCode: 'K',
            zone: 'K Block Academic Zone',
            venueName: 'Conference Hall',
            peopleCount: 44,
            capacity: 70,
            crowdLevel: 'MEDIUM',
        },
        {
            blockCode: 'HE-K',
            zone: 'Between HE Block and K Block',
            venueName: 'Basketball Court',
            peopleCount: 24,
            capacity: 40,
            crowdLevel: 'MEDIUM',
        },
        {
            blockCode: 'GROUND',
            zone: 'Main Ground (after L Block and J Block)',
            venueName: 'Football Ground',
            peopleCount: 54,
            capacity: 90,
            crowdLevel: 'MEDIUM',
        },
        {
            blockCode: 'GROUND',
            zone: 'Main Ground (after L Block and J Block)',
            venueName: 'Futsal Ground',
            peopleCount: 33,
            capacity: 50,
            crowdLevel: 'MEDIUM',
        },
        {
            blockCode: 'GROUND',
            zone: 'Main Ground (after L Block and J Block)',
            venueName: 'Cricket Ground',
            peopleCount: 47,
            capacity: 80,
            crowdLevel: 'MEDIUM',
        },
        {
            blockCode: 'GROUND',
            zone: 'Main Ground (after L Block and J Block)',
            venueName: 'Turf Cricket Pitch',
            peopleCount: 29,
            capacity: 40,
            crowdLevel: 'MEDIUM',
        },
        {
            blockCode: 'GROUND',
            zone: 'Main Ground (after L Block and J Block)',
            venueName: 'Badminton Pitch',
            peopleCount: 17,
            capacity: 30,
            crowdLevel: 'LOW',
        },
        {
            blockCode: 'GROUND',
            zone: 'Main Ground (after L Block and J Block)',
            venueName: 'Volleyball Court',
            peopleCount: 21,
            capacity: 36,
            crowdLevel: 'LOW',
        },
        {
            blockCode: 'GROUND',
            zone: 'Main Ground (after L Block and J Block)',
            venueName: 'Basketball Court (Main Ground)',
            peopleCount: 26,
            capacity: 40,
            crowdLevel: 'MEDIUM',
        },
    ],
    programPortfolio: [
        { name: 'B.E/B.Tech', courseCount: 8 },
        { name: 'UG Diploma', courseCount: 8 },
        { name: 'MBA/PGDM', courseCount: 3 },
        { name: 'BBA', courseCount: 6 },
        { name: 'M.Sc', courseCount: 20 },
        { name: 'BPT', courseCount: 1 },
        { name: 'BMRIT', courseCount: 1 },
        { name: 'BCA', courseCount: 3 },
        { name: 'GNM', courseCount: 3 },
        { name: 'B.Pharma', courseCount: 1 },
        { name: 'D.Pharma', courseCount: 1 },
        { name: 'M.A', courseCount: 5 },
        { name: 'B.A', courseCount: 4 },
        { name: 'BMLT', courseCount: 1 },
        { name: 'BOPTM', courseCount: 1 },
        { name: 'B.Sc (Post Basic)', courseCount: 1 },
        { name: 'B.Com', courseCount: 1 },
        { name: 'B.Ed', courseCount: 1 },
        { name: 'B.A (Hons)', courseCount: 1 },
        { name: 'After 10th Diploma', courseCount: 1 },
        { name: 'B.Des', courseCount: 1 },
        { name: 'MSN', courseCount: 1 },
        { name: 'MCA', courseCount: 1 },
        { name: 'BHMCT', courseCount: 1 },
        { name: 'MPT', courseCount: 1 },
        { name: 'M.Pharma', courseCount: 3 },
        { name: 'ANM', courseCount: 1 },
        { name: 'BPA', courseCount: 1 },
        { name: 'BSW', courseCount: 1 },
    ],
} as const;
